// import 'jQuery'
// import 'slick-carousel'
import 'material-design-icons/iconfont/material-icons.css'
import 'slick-carousel/slick/slick-theme.css'
import 'slick-carousel/slick/slick.css'

import '../semantic/dist/semantic.min.css'
import '../semantic/dist/semantic.min.js'
import './styles/index.scss'
import './scripts/main.js'